<?php 
/*
 * Template für ein Input-Feld type='text' oder type='date'
 * 
 * Benötigte Variablen:
 * 
 * $ausgabe['typ']          - Typ des Feldes
 * $ausgabe['feldname']     - Name und ID des Feldes
 * $ausgabe['beschriftung'] - Inhalt des Label-Elements
 * $ausgabe['fehler']       - Fehlermeldungen
 * 
 * 
 */
?>
<div>
    <label for="<?= $ausgabe['feldname'] ?>"><?= $ausgabe['beschriftung'] ?></label>
    <input type="<?= $ausgabe['typ'] ?>" name="<?= $ausgabe['feldname'] ?>" id="<?= $ausgabe['feldname'] ?>" value="<?= $form[$ausgabe['feldname']] ?>">
    <span><?= $ausgabe['fehler'][$ausgabe['feldname']] ?? '' ?></span>
</div>

