<?php
$ausgabe['titel'] = 'Tabelle';
include TEMPLATES . 'htmlkopf.phtml';
?>


<h3><?= number_format($anzahl, 0, ',', '.') ?> Veranstaltungen gefunden</h3>

<table>
    <caption>
        <div>
            <?php  include TEMPLATES . 'einfache_suche.phtml'; ?>
            <?php include TEMPLATES . 'paginator.phtml'; ?>
        </div>
    </caption>

    <?php
    $ausgabe['spaltenanzahl'] = 10;
    include TEMPLATES . 'spaltenanzahl.phtml';
    ?>

    <tr>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=vid">ID</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=name">Name</a></th>

        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=ort">Ort</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=plz">PLZ</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=datum">Datum</a></th>

<th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=beschreibung">Beschreibung</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=strasse">Strasse</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=stadt">Stadt</a></th>


        <th colspan="2">&nbsp;</th>
    </tr>
        <?php foreach ($veranstaltungen as $veranstaltung): ?>
        <tr>
    <?php foreach ($veranstaltung as $key => $value): ?>

                <td><?= $value ?></td>

    <?php endforeach; ?>      
            <td><a href="veranstaltung_aendern.php?updateid=<?= $veranstaltung['vid'] ?>">bearbeiten</a></td>
            <td><a href="veranstaltung_loeschen.php?loeschid=<?= $veranstaltung['vid'] ?>">löschen</a></td>
        </tr>
<?php endforeach; ?>
</table>
<?php
include TEMPLATES . 'htmlfuss.phtml';
?>
