<?php
$ausgabe['titel'] = 'Tabelle';
include TEMPLATES . 'htmlkopf.phtml';
?>


<h3><?= number_format($anzahl, 0, ',', '.') ?> Veranstaltungen gefunden</h3>

<table>
    <caption>
        <div>
            
            <?php include TEMPLATES . 'paginator.phtml'; ?>
        </div>
    </caption>

    <?php
    $ausgabe['spaltenanzahl'] = 10;
    include TEMPLATES . 'spaltenanzahl.phtml';
    ?>

    <tr>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=vid">ID</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=name">Name</a></th>

        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=ort">Ort</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=plz">PLZ</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=datum">Datum</a></th>

<th>&nbsp;</th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=strasse">Strasse</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=stadt">Stadt</a></th>


        
    </tr>
        <?php foreach ($veranstaltungen as $veranstaltung): ?>
        <tr>
    <?php foreach ($veranstaltung as $key => $value): ?>
            <?php if($key == 'name'): ?>
            <td><a href=""><?= $value ?></a></td>
                <?php else: ?>
                <td><?= $value ?></td>
                <?php endif; ?>
    <?php endforeach; ?>      
            
        </tr>
<?php endforeach; ?>
</table>
            <div>
                <form action="<?= $_SERVER['PHP_SELF'] ?>" name="suche" method="get">
                    <label for="suche">Name</label>
                    <input type="text" name="name" id="name" value="<?= $suchstring_name ?>">
                    
                    <label for="suche">Ort</label>
                    <input type="text" name="ort" id="ort" value="<?= $suchstring_ort ?>">
                    
                    <label for="suche">PLZ von</label>
                    <input type="text" name="plz_von" id="plz_von" value="<?= $suchstring_plz_von ?>">
                    
                    <label for="suche">PLZ bis</label>
                    <input type="text" name="plz_bis" id="plz_bis" value="<?= $suchstring_plz_bis ?>">
                    
                    <label for="suche">Datum</label>
                    <input type="date" name="datum" id="datum" value="<?= $suchstring_datum ?>">
                    
                    
                    
                    <button type="submit">suchen</button>
                </form>
            </div>
<?php
include TEMPLATES . 'htmlfuss.phtml';
