<?php
/*
 * Template für den leuchtende Spalten
 * 
 * Benötigte Variablen:
 * 
 * $ausgabe['spaltenanzahl']
 */

require_once 'funktionen_strings.php';
?>
  <colgroup>
                          <?php 
                          for($i = 0; $i <= $ausgabe['spaltenanzahl']; $i++):
                        ?>
                          <col>
                          
                          <?php
                          endfor;
                          ?>
                      </colgroup>